### ISSUE TITLE
Test Mode

### ISSUE THREAD

**Issue by joshbmartin** [ryantkerr/eCastingBar-Classic#8]
Doesn't seem to be a way to get rid of test mode? Maybe an unexpected return in the testModeMirror() function & its continuing to show the mirror?

**Comment by Zlopuk** [comment]
Yes i have the same problem

**Comment by Nightmane** [comment]
had the same problem, just disabling the addon entirely until I can find a fix for it

**Comment by Zwyk** [comment]
Sorry for taking long answering  this.
You just have to check "Hide Outline" in the options. We will rename this since it causes confusion.
